<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="ClientIntegrationRequest">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="APIKey" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="DeviceID" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="DeviceVersion" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="RequestUID" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="Function" fixed="GetCurrentActivity" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="FunctionVersion" fixed="1" minOccurs="1" maxOccurs="1" type="xs:decimal"/>
            <xs:element name="FunctionParameters" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>